### ISSUE TITLE
"nil" values seem to be serialized into data-types

### ISSUE THREAD

**Issue by florianb** [bbalser/json_serde#5]
Thank you very much for this library, i love it.
I am trying to serialize a structure making use of `nil` values and i expected them to be serialized as 'null' values:

```elixir
defmodule T do
defstruct _id: nil, _test: 1, t: nil
end

JsonSerde.serialize(%T{})
{:ok,
 "{\"_id\":{\"__data_type__\":\"atom\",\"value\":\"\"},\"_test\":1,\"t\":{\"__data_type__\":\"atom\",\"value\":\"\"},\"__data_type__\":\"Elixir.T\"}"}
```

Jason is mapping them correctly so i guess some kind of mapping is missing here.

I would open a PR to fix this, but i am unfortunately pretty new to Elixir and i haven't seen Brex before nor do i have a clue yet how it works at all..
I am willing to learn or help, so probably putting me in the right direction would allow me to propose a full PR with tests and so on.

**Comment by bbalser** [comment]
Great catch!  The problem is that nil is an atom and when the protocol is invoked it is hitting the impl for atoms.  If we put a new function head into the lib/json_serde/impls/atom.ex file that matches a nil and returns an {:ok, nil} tuple, I think that will solve the problem.  If you would like to give it a try please do, I will probably have time to get to it in the next few days.

Brian

**Comment by florianb** [comment]
Thank you for that opportunity @bbalser - it worked like you suggested.

I guess you should be able to come away with a PATCH version bump since i think it should be backward compatible.

Florian
